#!/usr/bin/env bash
# update-homebrew-formula.sh <tag> — regenerate the Homebrew tap formula for a
# new pi-harness release and push it to the tap repo.
#
# Called from .github/workflows/release.yml after the release is published.
# Downloads each macOS/Linux asset, computes its sha256, and rewrites
# Formula/pi-run.rb in forrestbthomas/homebrew-tap with the new version+hashes.
#
# Requires: GH_TOKEN (or gh auth), git push access to the tap repo.
set -euo pipefail

if [ $# -ne 1 ]; then
  echo "usage: $0 <tag>" >&2
  exit 2
fi
TAG="$1"
REPO="forrestbthomas/pi-harness"
TAP_REPO="forrestbthomas/homebrew-tap"
TAP_DIR="/tmp/homebrew-tap-update"

# Assets to include in the formula: <asset-name> <install-name>.
ASSETS=(
  "pi-run-darwin-arm64"
  "pi-run-darwin-amd64"
  "pi-run-linux-arm64"
  "pi-run-linux-amd64"
)

echo "== updating Homebrew formula for ${TAG} =="

# Clone the tap repo.
rm -rf "$TAP_DIR"
git clone --depth 1 "https://github.com/${TAP_REPO}.git" "$TAP_DIR"
cd "$TAP_DIR"

# Download each asset and compute its sha256.
# Use a simple key=value file (bash 3.2-safe; macOS ships bash 3.2).
SHA_FILE="/tmp/pi-run-shas-${TAG}.txt"
: > "$SHA_FILE"
for asset in "${ASSETS[@]}"; do
  url="https://github.com/${REPO}/releases/download/${TAG}/${asset}"
  tmp="/tmp/${asset}"
  # Retry the download: GitHub's CDN can lag the release API for a few
  # seconds; without retry a 404/HTML page would be hashed and pushed.
  ok=0
  for attempt in 1 2 3 4 5; do
    if curl -sL --fail "$url" -o "$tmp" && [ -s "$tmp" ]; then
      ok=1
      break
    fi
    echo "  retry ${attempt}: download of ${asset} failed, retrying..." >&2
    sleep 3
  done
  if [ "$ok" -ne 1 ]; then
    echo "ERROR: failed to download ${asset} from ${url}" >&2
    exit 1
  fi
  sha=$(shasum -a 256 "$tmp" | cut -d' ' -f1)
  echo "${asset} ${sha}" >> "$SHA_FILE"
  echo "  ${asset}: ${sha}"
done

sha_of() { grep "^$1 " "$SHA_FILE" | awk '{print $2}'; }

# Generate the formula.
cat > Formula/pi-run.rb << RUBY_EOF
# typed: false
# frozen_string_literal: true

# Homebrew formula for pi-run — the pi-harness CLI.
# Installs the prebuilt binary for the user's platform from the GitHub release.
# NOTE: generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class PiRun < Formula
  desc "Provider-agnostic coding-agent harness CLI (Pi + DeepEval)"
  homepage "https://github.com/forrestbthomas/pi-harness"
  version "${TAG}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/${REPO}/releases/download/${TAG}/pi-run-darwin-arm64"
      sha256 "$(sha_of pi-run-darwin-arm64)"

      def install
        bin.install "pi-run-darwin-arm64" => "pi-run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/${REPO}/releases/download/${TAG}/pi-run-darwin-amd64"
      sha256 "$(sha_of pi-run-darwin-amd64)"

      def install
        bin.install "pi-run-darwin-amd64" => "pi-run"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/${REPO}/releases/download/${TAG}/pi-run-linux-arm64"
      sha256 "$(sha_of pi-run-linux-arm64)"

      def install
        bin.install "pi-run-linux-arm64" => "pi-run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/${REPO}/releases/download/${TAG}/pi-run-linux-amd64"
      sha256 "$(sha_of pi-run-linux-amd64)"

      def install
        bin.install "pi-run-linux-amd64" => "pi-run"
      end
    end
  end

  test do
    system "#{bin}/pi-run", "version"
  end
end
RUBY_EOF

# Verify syntax.
ruby -c Formula/pi-run.rb

# Commit and push.
git add Formula/pi-run.rb
git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
  commit -m "Update pi-run formula to ${TAG}"
git push origin main

echo "== done: tap updated to ${TAG} =="
